#Матричная алгебра
Очень понравился маленький урок по матричной алгебре из курса <a href="https://www.coursera.org/course/stats1">Statistics One</a> от Coursera. Вот <a href="https://github.com/boboppie/coursera-course-statistics_one/blob/master/week3/notes/lecture_slides-Stats1.08B.pdf">ссылка</a> на слайды самого урока. Упражнение, которое я хочу повторить начинается на 19-ом слайде. Смыл упражнения заключается в том, чтобы путем различных действий над исходной матрицей получить матрицу корреляций.Я буду использовать объект matrix из numpy.

In [8]:
import numpy as np

Создадим матрицу как в уроке.

In [9]:
x_np = np.matrix([[3, 2, 3],
                   [3, 2, 3],
                   [2, 4, 4],
                   [4, 3, 4],
                   [4, 4, 3],
                   [5, 4, 3],
                   [2, 5, 4],
                   [3, 3, 2],
                   [5, 3, 4],
                   [3, 5, 4]])

Узнаем форму матрицы. Она понадобиться нам для создания вектором соразмерных исходной матрице.

In [10]:
x_np.shape

(10, 3)

Можно сказать, что у нас есть 3 переменные и десять записей о каждой из них. Корреляцию этих трех переменных я и буду выводить. Для начала получим вектор из единиц равный длине исходной матрицы.

In [13]:
n1 = np.matrix([1]*x_np.shape[0])
n1

matrix([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

Теперь умножим этот вектор на исходную матрицу и почим вектор состоящий из сумм по каждой переменной.

In [15]:
t_1p = n1 * x_np
t_1p

matrix([[34, 35, 34]])

Следующим дейсвием получим вектор из средних значений по каждой переменной. Для этого умножим вектор сумм на длину матрицу в -1-ой степени.

In [16]:
m_1p = t_1p * matrix.shape[0]**-1
m_1p

matrix([[ 3.4,  3.5,  3.4]])

Теперь умножим вектор средних на вертикальную матрицу из единиц (по длине исходной) и получим матрицу из средних, которая по форме будет соответствовать исходной матрице.

In [18]:
m_np = r1.T * m_1p
m_np

matrix([[ 3.4,  3.5,  3.4],
        [ 3.4,  3.5,  3.4],
        [ 3.4,  3.5,  3.4],
        [ 3.4,  3.5,  3.4],
        [ 3.4,  3.5,  3.4],
        [ 3.4,  3.5,  3.4],
        [ 3.4,  3.5,  3.4],
        [ 3.4,  3.5,  3.4],
        [ 3.4,  3.5,  3.4],
        [ 3.4,  3.5,  3.4]])

Вычтем матрицу средних из исходной матрицы и получим матрицу отклонения от средних.

In [21]:
d_np = x_np - m_np
d_np

matrix([[-0.4, -1.5, -0.4],
        [-0.4, -1.5, -0.4],
        [-1.4,  0.5,  0.6],
        [ 0.6, -0.5,  0.6],
        [ 0.6,  0.5, -0.4],
        [ 1.6,  0.5, -0.4],
        [-1.4,  1.5,  0.6],
        [-0.4, -0.5, -1.4],
        [ 1.6, -0.5,  0.6],
        [-0.4,  1.5,  0.6]])

Умножим транспонированную матрицу отклонений на саму матрицу отклонений и получим по диагонали квадраты отклонений самих перемнных и квадраты разницу отклонений между всеми переменными в остальных частях матрицы. Например элемент (1,2) показывает квадрат разницу отклонений от средних первой и второй переменной.

In [24]:
s_xx = d_np.T * d_np
s_xx

matrix([[ 10.4,  -2. ,  -0.6],
        [ -2. ,  10.5,   3. ],
        [ -0.6,   3. ,   4.4]])

Далее можно получить матрицу диспесрий и ковариации. Для этого умножим матрицу полученныю в предыдущем действии на а длину исходной матрицу в -1-ой степени, т.е. просто разделим на кол-во элементов в каждой переменной.

In [26]:
c_xx = s_xx * matrix.shape[0]**-1
c_xx

matrix([[ 1.04, -0.2 , -0.06],
        [-0.2 ,  1.05,  0.3 ],
        [-0.06,  0.3 ,  0.44]])

И снова по диагонале расположились дисперсии для каждой переменной, а в остальных элементах матрицу ковариации для каждой пары переменных. Обратите внимание, что элементы над и под диаганалью абсолютно одинаковые, это и очевидно - ковариция между, например 1 и 2 переменной и 2 и 1 должны быть равны.

Теперь получим диагональную матрицу стандартных отклонений по нашим трем переменным. Сначала рассчитаем сами стандартные отклонений. Для это возмем дисперсию каждой переменной (диагональ предыдущей матрицы) и извлечем из нее квадратный корень.

In [39]:
stds = np.sqrt(c_xx.diagonal())
stds

matrix([[ 1.0198039 ,  1.02469508,  0.66332496]])

Теперь создадим квадратную матрицу из нулей по количеству перемнных в исходной матрице и вставим в нее стандартные отклонения.

In [43]:
s_xx = np.zeros((3,3),float)
np.fill_diagonal(s_xx,stds)
s_xx = np.matrix(s_xx)
s_xx

matrix([[ 1.0198039 ,  0.        ,  0.        ],
        [ 0.        ,  1.02469508,  0.        ],
        [ 0.        ,  0.        ,  0.66332496]])

Осталось последнее действие - получить матрицу корреляций. Для этого инвертированную матрицу стандартных отклонений нажну умножить на матрицу дисперсий и ковариаций, а потом полученный результат еще раз на инвертированную матрицу стандартных отклонений. Это действие эквивалентно тому, что каждую коварицию делим сначала на стандартное отклонение одной переменной, а потом другой.

In [48]:
r_xx = s_xx.I*c_xx*s_xx.I
r_xx

matrix([[ 1.        , -0.19138975, -0.08869686],
        [-0.19138975,  1.        ,  0.44136741],
        [-0.08869686,  0.44136741,  1.        ]])

Вот и все. Предлагаю повторить этот эксперимент по памяти, чтобы лучше все понять.