In [1]:
import numpy as np

In [7]:
def get_bootstrap_samples(data, n_samples):
    indices = np.random.randint(0, len(data), (n_samples, len(data)))
    samples = data[indices]
    return samples

def stat_intervals(stat, alpha):
    boundaries = np.percentile(stat, [100 * alpha / 2., 100 * (1 - alpha / 2.)])
    return boundaries

def conf_int(data,stat_func,alpha=0.05,n_samples=1000):
    scores = [stat_func(sample) for sample in get_bootstrap_samples(data,n_samples)]
    return stat_intervals(scores, alpha)

def diff_conf_int(a,b,stat_func,alpha=0.05,n_samples=1000):
    scores_a = [stat_func(sample) for sample in get_bootstrap_samples(a,n_samples)]
    scores_b = [stat_func(sample) for sample in get_bootstrap_samples(b,n_samples)]
    delta_scores = [x[0] - x[1] for x in zip(scores_a,scores_b)]
    return stat_intervals(delta_scores, alpha)

In [8]:
np.random.seed(0)
a = np.random.normal(size=1000)
b = np.random.normal(loc=2,size=1000)

In [9]:
np.random.seed(0)
conf_int(a,np.median)

array([-0.11631365,  0.01042467])

In [10]:
np.random.seed(0)
conf_int(b,np.median)

array([ 1.96787223,  2.08685924])

In [11]:
np.random.seed(0)
diff_conf_int(b,a,np.median)

array([ 1.99599551,  2.17336498])